### ISSUE TITLE
RFE: a switch to disable DNS lookups for source IPs

### ISSUE THREAD

**Issue by siebenmann** [SuperQ/chrony_exporter#24]
Looking up the names of source IPs in DNS has various problems. One is that it can take a while; another is that the resulting DNS names can change over time (for a constant IP), which will have the effect of creating a different metric series (since the labels will change). It would be nice to have a command line switch that could be used to disable it in case people don't want the various effects.

(Since the host names are added to the label with a '.' at the end, you can't even necessarily cross-join on the source_name label to series from different sources, which are likely to not have a terminal '.'.)

**Comment by SuperQ** [comment]
Yup, that's something worth adding.
