### ISSUE TITLE
collector/sources.go should sort the list of DNS names before adding it to the label

### ISSUE THREAD

**Issue by siebenmann** [SuperQ/chrony_exporter#25]
A single IP may have multiple DNS names (PTR records), and I don't believe that net.LookupAddr() makes any promises that these names are returned in a consistent order over time. In the current code, the names returned are passed through to a metric label in the order that the code gets them; if this order changes, the metric label will change, which will cause Prometheus to see it as a new metric series since the labels are different. Because of this effect of changing the label value, I believe that collector/sources.go should sort the list of returned DNS names before turning them into a label.

One such time server (or time server pool) is time.nrc.ca, where the IPs involved all have two PTRs, one to an individual name such as time11.nrc.ca and the other to the pool name.

**Comment by SuperQ** [comment]
Yes, that is a good idea.
