### ISSUE TITLE
Publish container image 

### ISSUE THREAD

**Issue by gberche-orange** [SuperQ/chrony_exporter#31]
Thanks for sharing this chrony exporter with the community !

I did not find a public container image yet.

Could a github workflow + an image stored.published from github container registry help (see for instance the following related blog https://dev.to/willvelida/pushing-container-images-to-github-container-registry-with-github-actions-1m6b ) ?

**Comment by SuperQ** [comment]
The container image is here: https://quay.io/repository/superq/chrony-exporter

**Comment by SuperQ** [comment]
Added some docs: https://github.com/SuperQ/chrony_exporter/pull/32

**Comment by gberche-orange** [comment]
Great, thanks a lot Ben !
