### ISSUE TITLE
Invalid metric values

### ISSUE THREAD

**Issue by alkolexx** [SuperQ/chrony_exporter#66]
Hello!
If I enabled --collector.serverstats - then i get metric "chrony_up 0", but chrony is enabled and work fine
If I disabled --collector.serverstats - then i get metric "chrony_up 1"
Version chrony_exporter 0.9.0

**Comment by alkolexx** [comment]
Thanks!

**Comment by Gaozizhong** [comment]
大家好，当我配置完--chrony.address="unix:///run/chrony/chronyd.sock参数后出现了以下报错，这是怎么回事呢？
ts=2024-07-21T01:50:19.140Z caller=collector.go:183 level=debug scrape_id=1 msg="Couldn't get serverstats" err="got wrong 'serverstats' response: &{{'\\x06' \"reply\" '\\x00' '\\x00' '6' '\\x16' \"SUCCESS\" '\\x00' '\\x00' '\\x00' '\\x02' '\\x00' '\\x00'} {'𢘚' '\\x00' '0' '\\x00' '\\x00' '\\x00' '\\x00' '\\x00'}}"
