### ISSUE TITLE
Serverstats don't work on Chrony 4.5

### ISSUE THREAD

**Issue by mdavids** [SuperQ/chrony_exporter#82]
Am I doing something wrong? 

Debug logging shows:

`ts=2024-06-12T12:23:23.546Z caller=collector.go:183 level=debug scrape_id=2 msg="Couldn't get serverstats" err="not implemented reply type 25 from &{Version:6 PKTType:reply Res1:0 Res2:0 Command:54 Reply:25 Status:SUCCESS Pad1:0 Pad2:0 Pad3:0 Sequence:2 Pad4:0 Pad5:0}"`

Started with:

chrony_exporter --web.config.file=/web-config.yml --web.listen-address=198.51.100.123:9123 --web.listen-address=[2001:db8::123]:9123 --log.level=debug --chrony.address=unix:///run/chrony/chronyd.sock --collector.chmod-socket --collector.sources --collector.serverstats --no-collector.dns-lookups

chronyd (chrony) version 4.5 (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP +SCFILTER +SIGND +ASYNCDNS +NTS +SECHASH +IPV6 -DEBUG)

on  x86_64 Linux.

Probably depends on: https://github.com/facebook/time/issues/363

Also wondering is this should be a debug message or a warning? https://github.com/SuperQ/chrony_exporter/blob/1826c4053073f53d538776203838f79c2ef92085/collector/collector.go#L183

**Comment by SuperQ** [comment]
Yea, that issue looks related. I wonder if we can expose these packet issues in the exporter.

**Comment by mdavids** [comment]
There is now a pull request: https://github.com/facebook/time/pull/367

I assume some work also needs to be done on the chrony_exporter side?

**Comment by SuperQ** [comment]
At a minimum, we will need to update the library version.

**Comment by mdavids** [comment]
Still waiting for the pull request to come through.

**Comment by spaullilly** [comment]
Adding comment just to add that I"m affected by this and am waiting for the resolution.

**Comment by mdavids** [comment]
It works - thank you!
